[tool.poetry]
name = "roshi-rag"
version = "0.1.0"
description = "AI Agentic approach project for Roshi AI"
authors = ["joao machado <joovitm@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "*"}
langgraph = "*"
langsmith = "*"
python-dotenv = "*"
langchain-ollama = "*"
ruff = "*"
flake8 = "*"
pre-commit = "*"
pytest = "*"
pytest-asyncio = "*"
asyncpg = "*"
psycopg2-binary = "*"
langgraph-checkpoint-postgres = "*"
psycopg-binary = "*"
langfuse = "*"
langchain-text-splitters = "*"
langchain-community = "*"
langchain-core = "*"
beautifulsoup4 = "*"
lxml = "*"
faiss-cpu = "*"
ipykernel = "^6.30.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
